# **K-Means Clustering**

In [23]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
#loading datasets
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [25]:
path = "/content/drive/MyDrive/emnist-letters-test.csv"

DFPD = pd.read_csv(path)

DF0 = DFPD.to_numpy()

In [ ]:
#first tried for one iteration then extended idea to form loop for better results.

In [26]:
DF0.shape

(14799, 785)

In [27]:
DF1 = DF0[:,1:]

In [28]:
Int = [Int for Int in range(0,14800)]

In [29]:
pd.DataFrame(Int)

           0
0          0
1          1
2          2
3          3
4          4
...      ...
14795  14795
14796  14796
14797  14797
14798  14798
14799  14799

[14800 rows x 1 columns]

In [30]:
n = 14799
k = 19

In [31]:
centroid = DF1[np.random.choice(Int, 19, replace = False)]
pd.DataFrame(centroid)

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
centroid.shape
DF1.shape

(14799, 784)

In [33]:
euc_list = []

for i in range(19):
  euc_dist = 0
  euc_dist = np.sqrt(np.sum(((DF1 - centroid[i])**2), axis=1)) 
  
  euc_list.append(euc_dist)

  

pd.DataFrame(euc_list)

,0,1,2,3,4,5,6,7,8,9,...,14789,14790,14791,14792,14793,14794,14795,14796,14797,14798
0,3235.123027,2827.754586,3192.448120,3088.728541,3045.985226,3080.353389,3200.397632,3010.504609,3221.123872,3321.179459,...,3173.942501,3160.120093,3058.021746,2986.266231,3098.036959,3178.952029,2977.077762,3032.858223,3204.311627,3239.297300
1,2965.662321,3002.376059,3248.841794,2778.632397,3065.624569,3060.111599,3009.371529,3026.649633,3326.144765,3252.623095,...,2642.109952,3084.761093,2632.946069,2590.776718,2652.375728,3070.157325,2399.978333,2698.194396,2976.482656,3080.407603
2,2902.662915,3233.890691,3224.168730,3259.120280,2927.065254,3116.151793,3348.778285,3482.982486,2965.804107,2639.955681,...,2602.504563,2956.596692,3038.576970,3063.581074,2388.063651,3104.815776,3157.857027,2508.522274,2597.958429,2811.215396
3,3277.571357,2826.361442,2964.931365,3275.891482,3054.436609,2894.176912,3209.588136,3397.181920,3278.712552,2942.907406,...,2932.885610,2848.806066,2510.092030,2990.577703,2703.939718,2547.829468,3188.069165,2530.695952,2937.784539,2583.288602
4,3172.036412,2749.976727,3276.430832,2565.814101,2940.167342,2871.158825,3035.051070,2927.723006,3278.440330,2986.529591,...,2625.433107,2738.539209,2970.626702,2666.055888,3036.472460,2917.476307,2592.725593,2830.427000,2937.067074,2845.953794
5,3211.164586,2568.588912,3043.889617,2712.468433,2598.349284,2947.443977,3130.800217,3055.037643,3176.532701,3180.802100,...,3136.809526,3018.555615,2748.286375,3131.711513,3497.765572,2799.641227,2759.356628,2909.877661,3371.095074,3176.822312
6,3045.227085,2681.164486,3227.569364,2491.938402,3215.283658,2747.192385,2762.429004,2569.322284,3265.987753,2854.920664,...,2550.750086,2677.604153,2999.586305,2432.758311,3079.278812,2746.910810,2464.802020,2900.975353,2969.634658,2705.864372
7,3065.685242,3088.827447,3050.523889,2907.641140,3475.298117,3127.135430,3198.307052,3322.135608,3462.463285,3088.682567,...,2354.846492,2974.155342,2938.350217,2770.656420,2669.700358,2901.321940,2661.271313,2920.705052,2174.807578,3040.084538
8,2908.071182,3107.972812,3516.789445,2490.918104,3038.512630,2671.412735,2676.659485,2722.806089,2971.111240,2911.196661,...,2824.943893,2907.272949,2918.825449,2362.186910,2797.783408,2987.069969,2753.706775,2821.885894,3215.692460,2618.212367
9,3063.491635,2359.753801,2430.978198,2797.741589,3071.257397,2804.193467,2866.404193,2782.064341,3536.524424,3035.175942,...,2629.408869,2674.795506,2903.780123,2806.555896,2949.168527,2538.723695,2543.515677,2686.107034,3075.583034,2887.854048
10,2594.429417,2887.140627,3201.282243,2918.511778,3381.537964,2792.273626,2959.903039,2899.957069,3471.370911,3007.671192,...,2518.509877,2587.957109,2807.967236,2266.293670,2459.473927,2517.098528,2547.323105,2867.173172,2447.208205,2743.837094
11,3210.774517,3067.468337,3016.677477,2774.381012,2891.329106,3072.067219,3252.652302,3239.382040,3276.869085,2846.431274,...,2838.279937,3171.349397,2929.777978,3165.271868,3341.017061,3221.958721,2905.287249,2883.763340,3172.022226,3202.766773
12,2810.013167,2738.235746,3068.198494,2719.159613,3220.750378,2948.620694,2976.007728,3040.215617,3297.982717,3037.014323,...,2653.845512,2610.618318,2591.056927,2389.462910,2528.132908,2693.713979,2271.390103,2847.826891,2421.874481,2744.336714
13,2883.872570,2886.963803,3328.680069,3133.382517,2865.994766,2969.998485,2949.267197,2953.558532,3132.954676,2917.773295,...,2687.219195,2702.651106,2916.431895,2440.406933,2444.161410,2845.639471,2830.570261,2819.027315,2829.734086,2631.080196
14,2893.491835,2601.900075,3021.786392,2738.323940,3100.509958,2916.695905,3131.830615,3239.059431,3053.125775,2883.758138,...,2777.244858,2480.988311,2393.226483,2385.742652,2494.419572,2113.171550,2516.487234,2216.440164,2221.467308,2867.982741
15,3372.829673,2796.954236,3078.288810,2743.402085,2540.229320,2353.782913,2721.828797,3013.704199,2998.033355,2738.173479,...,3284.867729,2775.661723,2881.576999,3083.935635,3283.251133,2581.042619,3038.371110,2837.890766,3378.185904,2551.608512
16,3223.851578,3004.948585,3253.402680,2919.554418,3042.877257,2977.973976,3191.776778,3170.957899,3328.295510,3065.072756,...,2624.664740,3036.416144,2679.203800,2706.832097,3069.231337,3055.215213,2852.286451,2525.109701,3211.455278,2929.348221
17,2963.599501,2660.249424,3273.400067,2724.440677,3340.257026,2683.849847,2601.582211,2559.060179,3451.575003,2761.755963,...,2512.472089,2399.822493,2955.707022,2342.474973,2809.381783,2584.204133,2382.461122,2912.706645,2833.460781,2568.478538
18,3078.865700,2778.323775,3098.368280,2708.359097,2399.488487,2599.631512,3137.278120,2951.235504,2629.834215,2866.476932,...,2825.107078,2835.934767,2889.052440,2758.466422,2718.741988,2873.334474,2940.571543,2477.849874,3120.600263,2324.959785

In [34]:
closest = np.argmin(euc_list, axis = 0)

In [35]:
np.reshape(closest, (14799,1))

array([[10],
       [ 9],
       [ 9],
       ...,
       [14],
       [ 7],
       [18]])

In [36]:
pd.DataFrame(closest)

        0
0      10
1       9
2       9
3       8
4      18
...    ..
14794  14
14795  12
14796  14
14797   7
14798  18

[14799 rows x 1 columns]

In [37]:
arr = DF1[np.where(closest == 0)]

In [38]:
cen = np.mean(arr, axis =0)

In [39]:
cen.tolist()

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.01556420233463035,
 0.023346303501945526,
 0.038910505836575876,
 0.07003891050583658,
 0.06614785992217899,
 0.0622568093385214,
 0.01556420233463035,
 0.0311284046692607,
 0.08560311284046693,
 0.11284046692607004,
 0.14396887159533073,
 0.0933852140077821,
 0.1828793774319066,
 0.245136186770428,
 0.24124513618677043,
 0.19844357976653695,
 0.17120622568093385,
 0.13618677042801555,
 0.19066147859922178,
 0.10894941634241245,
 0.03501945525291829,
 0.01556420233463035,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.08560311284046693,
 0.8132295719844358,
 1.377431906614786,
 3.2490272373540856,
 3.964980544747082,
 3.735408560311284,
 4.533073929961089,
 3.431906614785992,
 4.116731517509727,
 5.443579766536965,
 7.739299610894942,
 9.167315175097276,
 8.988326848249027,
 9.038910505836576,
 8.517509727626459,
 7.875486381322958,
 6.856031128404669,
 5.657587548638133,
 5.330739299610895,
 4.035019455252918,
 2.575875486381323,
 1.5214007782101167,
 0.8365758754863813,
 0.1517509727626459,
 0.0,
 0.0,
 0.0,
 0.0,
 0.5369649805447471,
 2.186770428015564,
 4.8599221789883265,
 11.766536964980546,
 14.957198443579767,
 17.09338521400778,
 23.24124513618677,
 29.342412451361866,
 35.68482490272373,
 40.0,
 46.17898832684825,
 48.91439688715953,
 46.35019455252918,
 42.40856031128405,
 36.88326848249027,
 32.53307392996109,
 28.443579766536963,
 24.80933852140078,
 20.95330739299611,
 16.494163424124512,
 12.914396887159533,
 9.194552529182879,
 5.214007782101167,
 1.2762645914396886,
 0.027237354085603113,
 0.0,
 0.0,
 0.023346303501945526,
 2.124513618677043,
 7.073929961089494,
 12.797665369649806,
 22.579766536964982,
 30.96887159533074,
 44.252918287937746,
 63.08560311284047,
 80.28015564202335,
 93.34630350194553,
 99.07003891050584,
 101.3035019455253,
 98.69260700389106,
 92.03112840466926,
 83.284046692607,
 73.38132295719845,
 65.14396887159533,
 55.38132295719844,
 47.217898832684824,
 41.038910505836576,
 32.252918287937746,
 26.404669260700388,
 18.36964980544747,
 10.354085603112841,
 2.8910505836575875,
 0.058365758754863814,
 0.0,
 0.0,
 0.07003891050583658,
 4.357976653696498,
 12.649805447470817,
 21.21011673151751,
 37.268482490272376,
 58.84824902723735,
 89.65369649805447,
 121.13618677042801,
 145.00778210116732,
 158.568093385214,
 159.6770428015564,
 155.19066147859922,
 143.86770428015564,
 129.27626459143968,
 113.49027237354086,
 99.05447470817121,
 85.3307392996109,
 71.48249027237354,
 61.12451361867704,
 52.961089494163424,
 44.540856031128406,
 37.175097276264594,
 26.47859922178988,
 13.922178988326849,
 4.171206225680934,
 0.07782101167315175,
 0.0,
 0.0,
 0.04669260700389105,
 4.046692607003891,
 14.354085603112841,
 30.980544747081712,
 62.05058365758755,
 99.06225680933852,
 142.4863813229572,
 174.63035019455253,
 191.00389105058366,
 194.715953307393,
 186.8171206225681,
 174.09727626459144,
 157.1400778210117,
 139.4863813229572,
 120.14007782101167,
 103.60311284046692,
 89.01556420233463,
 72.85992217898833,
 61.63424124513619,
 53.719844357976655,
 45.77431906614786,
 39.3852140077821,
 29.105058365758754,
 15.801556420233464,
 4.428015564202335,
 0.0622568093385214,
 0.0,
 0.0,
 0.038910505836575876,
 4.151750972762646,
 18.571984435797667,
 45.57976653696498,
 93.92607003891051,
 144.1011673151751,
 183.24902723735408,
 196.87937743190662,
 195.43579766536965,
 184.7898832684825,
 174.01945525291828,
 162.10894941634243,
 152.3229571984436,
 139.70038910505838,
 117.0,
 94.4591439688716,
 79.22568093385215,
 64.80155642023347,
 54.221789883268485,
 49.4124513618677,
 44.6692607003891,
 39.31517509727627,
 30.988326848249027,
 17.155642023346303,
 4.595330739299611,
 0.04669260700389105,
 0.0,
 0.0,
 0.07392996108949416,
 5.976653696498055,
 28.19066147859922,
 67.32684824902724,
 129.52529182879377,
 175.32684824902725,
 195.9455252918288,
 185.03112840466926,
 157.6614785992218,
 134.06614785992218,
 130.5214007782101,
 139.82490272373542,
 147.2373540856031,
 140.40856031128405,
 116.01556420233463,
 87.67704280155642,
 68.57587548638132,
 58.66147859922179,
 52.70817120622568,
 49.6692607003891,
 47.12062256809339,
 42.27626459143969,
 33.583657587548636,
 19.653696498054476,
 5.171206225680934,
 0.054474708171206226,
 0.0,
 0.0,
 0.13618677042801555,
 9.754863813229573,
 44.06225680933852,
 101.00389105058366,
 159.7704280155642,
 187.0739299610895,
 180.10894941634243,
 146.43579766536965,
 105.0,
 82.46692607003891,
 91.18677042801556,
 118.39299610894942,
 145.94941634241246,
 148.5136186770428,
 121.05836575875486,
 86.07003891050584,
 65.21400778210116,
 57.14007782101167,
 55.35408560311284,
 51.463035019455255,
 51.54474708171206,
 47.14785992217899,
 38.26070038910506,
 22.762645914396888,
 6.392996108949417,
 0.08171206225680934,
 0.0,
 0.0,
 0.3229571984435798,
 13.75875486381323,
 63.15175097276265,
 131.31906614785993,
 180.96498054474708,
 181.66926070038912,
 150.0544747081712,
 101.35019455252919,
 58.5875486381323,
 45.46692607003891,
 66.86770428015564,
 107.42412451361868,
 148.40856031128405,
 158.4941634241245,
 129.84824902723736,
 92.2295719844358,
 69.3579766536965,
 60.673151750972764,
 60.29961089494164,
 59.62645914396887,
 58.054474708171206,
 52.69260700389105,
 41.53307392996109,
 25.147859922178988,
 7.972762645914397,
 0.13229571984435798,
 0.0,
 0.0,
 0.5097276264591439,
 19.132295719844358,
 82.57198443579766,
 152.2101167315175,
 190.4396887159533,
 171.9260700389105,
 123.42412451361868,
 70.28015564202335,
 35.05058365758755,
 30.754863813229573,
 56.12062256809339,
 102.9727626459144,
 151.01945525291828,
 164.06225680933852,
 136.8326848249027,
 99.69260700389106,
 73.45525291828794,
 64.16342412451363,
 65.27237354085604,
 66.69260700389106,
 66.4863813229572,
 61.61867704280156,
 47.91828793774319,
 30.264591439688715,
 9.933852140077821,
 0.17120622568093385,
 0.0,
 0.0,
 0.5953307392996109,
 25.48249027237354,
 101.1828793774319,
 166.704280155642,
 190.4785992217899,
 158.51750972762645,
 104.61089494163424,
 54.68093385214008,
 27.610894941634243,
 31.867704280155642,
 59.719844357976655,
 107.64591439688716,
 154.01556420233464,
 166.6498054474708,
 138.5603112840467,
 102.1750972762646,
 74.84046692607004,
 63.54474708171206,
 67.33463035019456,
 69.96887159533074,
 72.36575875486382,
 68.37354085603113,
 53.96498054474708,
 34.78599221789883,
 11.101167315175097,
 0.17898832684824903,
 0.0,
 0.0,
 0.6848249027237354,
 30.55252918287938,
 114.45525291828794,
 176.284046692607,
 188.568093385214,
 148.0466926070039,
 91.09338521400778,
 48.21011673151751,
 31.396887159533073,
 41.599221789883266,
 70.52918287937743,
 115.29961089494164,
 158.12062256809338,
 167.64591439688715,
 138.03501945525292,
 103.00389105058366,
 77.23346303501945,
 65.92217898832685,
 70.13229571984436,
 74.86381322957199,
 78.42801556420234,
 75.18677042801556,
 60.82879377431907,
 38.715953307392994,
 12.272373540856032,
 0.19455252918287938,
 0.0,
 0.0,
 0.8093385214007782,
 32.69260700389105,
 117.39299610894942,
 176.83657587548637,
 182.80155642023345,
 141.78210116731518,
 87.29182879377431,
 53.8715953307393,
 46.03112840466926,
 61.007782101167315,
 90.84046692607004,
 129.7431906614786,
 164.4591439688716,
 168.87548638132296,
 136.50194552529183,
 101.12451361867704,
 80.28793774319067,
 70.01556420233463,
 76.51750972762646,
 83.10894941634241,
 89.852140077821,
 85.85992217898833,
 73.01945525291829,
 45.86770428015564,
 14.821011673151752,
 0.29961089494163423,
 0.0,
 0.0,
 0.8210116731517509,
 30.673151750972764,
 112.48249027237354,
 169.76653696498053,
 178.9455252918288,
 146.70817120622567,
 103.90661478599222,
 77.72373540856032,
 76.8443579766537,
 88.26459143968872,
 114.03112840466926,
 147.284046692607,
 174.4669260700389,
 171.28793774319067,
 138.6614785992218,
 105.9727626459144,
 87.68482490272373,
 79.91439688715953,
 86.2023346303502,
 93.42412451361868,
 99.50972762645914,
 95.50194552529183,
 81.98054474708171,
 54.12451361867704,
 17.71206225680934,
 0.32684824902723736,
 0.0,
 0.0,
 0.5797665369649806,
 25.80933852140078,
 99.77431906614785,
 157.37354085603113,
 178.31517509727627,
 162.3229571984436,
 132.99221789883268,
 110.42023346303502,
 110.6887159533074,
 118.69260700389106,
 137.85603112840468,
 163.30739299610894,
 178.7431906614786,
 166.3501945525292,
 136.4669260700389,
 109.70038910505836,
 96.49027237354086,
 96.61867704280155,
 102.56031128404669,
 106.78210116731518,
 113.7704280155642,
 108.08171206225681,
 91.82879377431907,
 60.4863813229572,
 19.260700389105057,
 0.46303501945525294,
 0.0,
 0.0,
 0.36964980544747084,
 19.90272373540856,
 83.05447470817121,
 142.431906614786,
 171.29182879377433,
 173.8715953307393,
 158.58365758754863,
 142.56420233463035,
 143.3929961089494,
 151.62645914396887,
 164.8054474708171,
 175.24513618677042,
 180.41634241245137,
 167.29182879377433,
 143.5214007782101,
 120.18677042801556,
 108.85603112840467,
 108.41634241245136,
 116.08560311284047,
 123.38132295719845,
 131.88715953307394,
 122.61867704280155,
 102.61089494163424,
 65.98832684824903,
 21.023346303501945,
 0.5680933852140078,
 0.0,
 0.0,
 0.26848249027237353,
 15.482490272373541,
 65.0,
 118.03501945525292,
 153.8171206225681,
 168.9182879377432,
 171.35408560311285,
 169.39688715953307,
 169.52918287937743,
 171.2295719844358,
 175.284046692607,
 173.42412451361866,
 173.6614785992218,
 167.92217898832683,
 155.40856031128405,
 138.70817120622567,
 130.5875486381323,
 128.9727626459144,
 136.9455252918288,
 146.74708171206225,
 152.6887159533074,
 141.52918287937743,
 115.21011673151752,
 73.20622568093385,
 23.801556420233464,
 0.5758754863813229,
 0.0,
 0.0,
 0.17120622568093385,
 10.373540856031129,
 45.47081712062257,
 86.86770428015564,
 123.05058365758755,
 146.99221789883268,
 160.8054474708171,
 165.24513618677042,
 162.7431906614786,
 160.9455252918288,
 157.69649805447472,
 154.1011673151751,
 156.72373540856032,
 159.39688715953307,
 160.34241245136187,
 152.2373540856031,
 147.84824902723736,
 143.8171206225681,
 152.7976653696498,
 166.52529182879377,
 170.30350194552528,
 155.87937743190662,
 122.7976653696498,
 76.50972762645914,
 24.21011673151751,
 0.5291828793774319,
 0.0,
 0.0,
 0.0311284046692607,
 4.638132295719845,
 27.49805447470817,
 57.77431906614786,
 83.31906614785993,
 106.6964980544747,
 124.6147859922179,
 130.09338521400778,
 128.52918287937743,
 123.50583657587549,
 117.39299610894942,
 115.64980544747081,
 121.86770428015564,
 130.59143968871595,
 138.3774319066148,
 140.431906614786,
 140.1284046692607,
 139.80933852140078,
 149.80933852140078,
 165.98443579766536,
 174.99610894941634,
 161.57198443579767,
 125.56031128404669,
 73.73540856031128,
 21.813229571984436,
 0.5330739299610895,
 0.0,
 0.0,
 0.007782101167315175,
 1.9883268482490273,
 16.638132295719846,
 37.67704280155642,
 55.87548638132296,
 66.29961089494164,
 77.62645914396887,
 81.6147859922179,
 82.36186770428016,
 77.83268482490273,
 74.29571984435798,
 74.55252918287938,
 79.85603112840467,
 88.7704280155642,
 98.73540856031128,
 106.09338521400778,
 110.78599221789884,
 116.44357976653697,
 127.06225680933852,
 145.88326848249028,
 161.30739299610894,
 153.3229571984436,
 118.80933852140078,
 69.88326848249027,
 18.879377431906615,
 0.4785992217898833,
 0.0,
 0.0,
 0.011673151750972763,
 1.424124513618677,
 9.630350194552529,
 21.470817120622566,
 32.976653696498055,
 36.82879377431907,
 39.47081712062257,
 41.478599221789885,
 42.459143968871594,
 41.98054474708171,
 41.77431906614786,
 40.80544747081712,
 42.81322957198444,
 47.42801556420233,
 56.52918287937743,
 64.61867704280155,
 73.08560311284047,
 84.14007782101167,
 98.49027237354086,
 116.99221789883268,
 132.6342412451362,
 126.62256809338521,
 96.50972762645914,
 55.21400778210117,
 14.346303501945526,
 0.48638132295719844,
 0.0,
 0.0,
 0.0,
 0.8482490272373541,
 5.883268482490273,
 11.67704280155642,
 16.46692607003891,
 18.14396887159533,
 19.50194552529183,
 19.48249027237354,
 18.59922178988327,
 19.346303501945524,
 18.50194552529183,
 17.90661478599222,
 18.8715953307393,
 21.972762645914397,
 25.926070038910506,
 34.175097276264594,
 41.809338521400775,
 49.1284046692607,
 60.0739299610895,
 76.12451361867704,
 87.1011673151751,
 84.19844357976653,
 63.505836575875485,
 35.03501945525292,
 9.949416342412452,
 0.311284046692607,
 0.0,
 0.0,
 0.0,
 0.21011673151750973,
 2.0428015564202333,
 4.4319066147859925,
 5.867704280155642,
 6.031128404669261,
 5.980544747081712,
 5.571984435797665,
 5.439688715953308,
 5.793774319066148,
 6.389105058365759,
 6.57976653696498,
 6.011673151750973,
 6.070038910505836,
 8.793774319066149,
 13.167315175097276,
 18.08171206225681,
 22.474708171206224,
 27.64980544747082,
 33.284046692607006,
 36.68093385214008,
 36.264591439688715,
 27.832684824902724,
 15.603112840466926,
 4.556420233463035,
 0.2140077821011673,
 0.0,
 0.0,
 0.0,
 0.019455252918287938,
 0.2801556420233463,
 0.8365758754863813,
 1.1245136186770428,
 1.2529182879377432,
 0.9922178988326849,
 0.8754863813229572,
 0.9727626459143969,
 1.0778210116731517,
 1.6420233463035019,
 2.307392996108949,
 1.9027237354085602,
 1.3307392996108949,
 1.4941634241245136,
 2.0389105058365757,
 2.684824902723735,
 4.64591439688716,
 6.544747081712062,
 8.101167315175097,
 7.428015564202335,
 6.715953307392996,
 5.622568093385214,
 2.4280155642023344,
 0.5175097276264592,
 0.10894941634241245,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.011673151750972763,
 0.01556420233463035,
 0.023346303501945526,
 0.01556420233463035,
 0.01556420233463035,
 0.01556420233463035,
 0.019455252918287938,
 0.04669260700389105,
 0.13229571984435798,
 0.07782101167315175,
 0.019455252918287938,
 0.01556420233463035,
 0.019455252918287938,
 0.007782101167315175,
 0.058365758754863814,
 0.2178988326848249,
 0.2178988326848249,
 0.07003891050583658,
 0.07392996108949416,
 0.0933852140077821,
 0.07782101167315175,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [40]:
def Kmeans_model(DF1, k, s):
  Int = [Int for Int in range(0,14800)]
  centroid = DF1[np.random.choice(Int, k, replace = False)]  
  for t in range(s):
    euc_list = []
  
    for i in range(k):
     euc_dist = 0
     euc_dist = np.sqrt(np.sum(((DF1 - centroid[i])**2), axis=1)) 
     euc_list.append(euc_dist)

    closest = np.argmin(euc_list, axis = 0) 
    centroidu = np.empty_like(centroid) 
    for j in range(k):
      arr = DF1[np.where(closest == j)]
      cen = 0
      cen = np.mean(arr, axis =0)
      centroidu[j] = cen
    
    if centroid.all == centroidu.all:
      break
    
    
    print(closest)
    
  centroid = centroidu
  return closest

# Clusters

In [41]:
A = Kmeans_model(DF1, 19, 100)

[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]

In [42]:
pd.DataFrame(A)

        0
0      18
1       7
2       7
3      17
4       6
...    ..
14794   7
14795  15
14796   6
14797  10
14798  10

[14799 rows x 1 columns]

In [43]:
if A[0] == A[1]:
  print(0)

In [44]:
if A[0] != A[1]:
  print(1)

1

In [48]:
A.tolist()

[18,
 7,
 7,
 17,
 6,
 17,
 12,
 15,
 3,
 10,
 17,
 7,
 5,
 6,
 11,
 12,
 3,
 12,
 13,
 11,
 12,
 12,
 12,
 5,
 14,
 2,
 11,
 3,
 7,
 9,
 6,
 10,
 9,
 10,
 7,
 9,
 18,
 3,
 11,
 10,
 7,
 7,
 5,
 7,
 11,
 14,
 7,
 12,
 3,
 11,
 7,
 13,
 11,
 7,
 3,
 3,
 2,
 12,
 14,
 5,
 2,
 14,
 7,
 11,
 9,
 6,
 6,
 8,
 6,
 5,
 2,
 9,
 7,
 16,
 14,
 13,
 3,
 13,
 2,
 7,
 5,
 5,
 7,
 12,
 6,
 7,
 14,
 5,
 9,
 7,
 11,
 17,
 7,
 16,
 5,
 7,
 14,
 5,
 9,
 3,
 6,
 3,
 2,
 11,
 5,
 14,
 6,
 2,
 2,
 9,
 14,
 6,
 6,
 7,
 13,
 7,
 7,
 13,
 13,
 7,
 5,
 6,
 4,
 6,
 2,
 5,
 17,
 7,
 4,
 18,
 13,
 13,
 12,
 11,
 12,
 2,
 3,
 9,
 6,
 7,
 2,
 12,
 5,
 6,
 12,
 2,
 7,
 6,
 18,
 5,
 3,
 7,
 5,
 7,
 7,
 7,
 18,
 4,
 13,
 18,
 6,
 13,
 7,
 10,
 17,
 6,
 7,
 17,
 2,
 8,
 11,
 9,
 6,
 5,
 10,
 9,
 5,
 13,
 7,
 5,
 12,
 17,
 6,
 3,
 11,
 6,
 2,
 6,
 5,
 10,
 12,
 12,
 9,
 9,
 6,
 2,
 2,
 2,
 11,
 16,
 16,
 6,
 2,
 14,
 9,
 7,
 5,
 5,
 12,
 7,
 17,
 5,
 7,
 17,
 2,
 11,
 9,
 13,
 11,
 2,
 2,
 7,
 2,
 18,
 6,
 2,
 9,
 2,
 9,
 17,
 11,
 9,
 9,
 5,
 3,
 18,
 6,
 1,
 2,
 12,
 7,
 8,
 6,
 3,
 3,
 13,
 6,
 3,
 11,
 14,
 9,
 5,
 3,
 4,
 3,
 2,
 14,
 18,
 7,
 14,
 9,
 12,
 9,
 6,
 5,
 7,
 17,
 2,
 5,
 12,
 8,
 2,
 12,
 2,
 12,
 5,
 5,
 11,
 10,
 3,
 5,
 11,
 11,
 4,
 12,
 5,
 5,
 8,
 7,
 3,
 12,
 6,
 11,
 3,
 18,
 11,
 17,
 6,
 15,
 2,
 11,
 11,
 7,
 2,
 11,
 11,
 5,
 13,
 12,
 2,
 7,
 6,
 5,
 13,
 3,
 6,
 2,
 3,
 13,
 18,
 14,
 12,
 11,
 7,
 7,
 2,
 9,
 6,
 5,
 7,
 12,
 6,
 9,
 6,
 11,
 9,
 5,
 7,
 7,
 5,
 7,
 4,
 9,
 7,
 13,
 11,
 7,
 2,
 10,
 9,
 5,
 13,
 5,
 17,
 13,
 5,
 11,
 18,
 18,
 13,
 11,
 18,
 3,
 2,
 3,
 2,
 6,
 12,
 7,
 3,
 9,
 3,
 5,
 3,
 7,
 7,
 6,
 2,
 5,
 12,
 11,
 2,
 14,
 6,
 9,
 9,
 5,
 12,
 17,
 13,
 2,
 2,
 18,
 13,
 5,
 9,
 9,
 14,
 11,
 13,
 5,
 11,
 11,
 6,
 3,
 18,
 6,
 3,
 3,
 2,
 6,
 14,
 2,
 12,
 4,
 2,
 6,
 2,
 2,
 17,
 8,
 13,
 2,
 5,
 13,
 5,
 11,
 18,
 5,
 6,
 2,
 11,
 5,
 11,
 12,
 6,
 3,
 7,
 10,
 6,
 11,
 5,
 6,
 11,
 3,
 3,
 14,
 14,
 18,
 12,
 7,
 10,
 11,
 7,
 9,
 11,
 7,
 6,
 9,
 2,
 7,
 5,
 2,
 3,
 7,
 3,
 6,
 9,
 11,
 12,
 12,
 2,
 11,
 2,
 11,
 6,
 12,
 4,
 14,
 6,
 2,
 18,
 18,
 6,
 3,
 14,
 7,
 18,
 6,
 3,
 7,
 18,
 11,
 3,
 7,
 2,
 7,
 5,
 3,
 14,
 14,
 2,
 2,
 3,
 7,
 3,
 7,
 13,
 3,
 3,
 3,
 7,
 2,
 11,
 6,
 8,
 16,
 6,
 7,
 2,
 11,
 6,
 12,
 11,
 13,
 2,
 12,
 8,
 13,
 2,
 6,
 2,
 18,
 14,
 2,
 5,
 7,
 18,
 5,
 11,
 12,
 16,
 18,
 3,
 5,
 12,
 13,
 14,
 2,
 3,
 5,
 6,
 7,
 7,
 6,
 7,
 2,
 6,
 5,
 13,
 17,
 2,
 12,
 18,
 13,
 5,
 3,
 12,
 4,
 6,
 13,
 2,
 13,
 14,
 6,
 5,
 10,
 7,
 5,
 3,
 9,
 12,
 1,
 3,
 3,
 9,
 2,
 7,
 12,
 5,
 5,
 5,
 2,
 6,
 7,
 7,
 2,
 3,
 9,
 12,
 5,
 6,
 11,
 6,
 6,
 5,
 13,
 12,
 7,
 13,
 7,
 6,
 7,
 3,
 11,
 11,
 9,
 18,
 11,
 7,
 18,
 9,
 6,
 12,
 6,
 13,
 4,
 12,
 13,
 13,
 3,
 12,
 3,
 3,
 3,
 9,
 5,
 7,
 7,
 5,
 5,
 1,
 14,
 12,
 6,
 11,
 2,
 4,
 2,
 14,
 9,
 6,
 12,
 12,
 6,
 12,
 5,
 12,
 6,
 3,
 14,
 6,
 18,
 6,
 6,
 7,
 11,
 7,
 10,
 9,
 2,
 5,
 11,
 11,
 6,
 4,
 13,
 13,
 9,
 14,
 7,
 7,
 13,
 2,
 13,
 6,
 7,
 6,
 18,
 11,
 6,
 12,
 13,
 12,
 6,
 9,
 6,
 2,
 14,
 14,
 7,
 18,
 6,
 7,
 11,
 18,
 11,
 16,
 6,
 7,
 3,
 7,
 5,
 6,
 3,
 3,
 7,
 2,
 3,
 11,
 10,
 14,
 14,
 6,
 14,
 3,
 12,
 6,
 18,
 13,
 5,
 12,
 2,
 3,
 13,
 2,
 3,
 16,
 6,
 7,
 7,
 7,
 6,
 11,
 6,
 11,
 14,
 2,
 7,
 7,
 3,
 9,
 6,
 14,
 17,
 12,
 2,
 4,
 11,
 5,
 14,
 7,
 7,
 7,
 11,
 3,
 7,
 13,
 2,
 11,
 4,
 13,
 12,
 11,
 5,
 8,
 13,
 7,
 2,
 9,
 18,
 6,
 2,
 3,
 6,
 9,
 6,
 7,
 12,
 14,
 6,
 7,
 6,
 18,
 14,
 7,
 12,
 3,
 7,
 18,
 2,
 18,
 6,
 15,
 4,
 4,
 1,
 1,
 17,
 1,
 11,
 4,
 15,
 9,
 3,
 18,
 9,
 15,
 11,
 17,
 6,
 11,
 13,
 11,
 4,
 11,
 9,
 15,
 11,
 5,
 11,
 13,
 15,
 15,
 17,
 9,
 6,
 4,
 11,
 17,
 16,
 16,
 18,
 1,
 6,
 3,
 1,
 9,
 18,
 11,
 18,
 9,
 1,
 15,
 15,
 18,
 16,
 5,
 17,
 3,
 13,
 15,
 4,
 13,
 11,
 3,
 17,
 14,
 17,
 3,
 15,
 15,
 18,
 3,
 6,
 4,
 3,
 9,
 15,
 1,
 12,
 17,
 11,
 9,
 11,
 13,
 9,
 11,
 13,
 9,
 8,
 10,
 4,
 1,
 16,
 9,
 4,
 17,
 13,
 15,
 6,
 11,
 4,
 15,
 15,
 10,
 15,
 6,
 7,
 4,
 15,
 1,
 15,
 16,
 16,
 1,
 1,
 7,
 11,
 12,
 15,
 16,
 17,
 9,
 9,
 3,
 11,
 18,
 4,
 11,
 18,
 18,
 9,
 15,
 9,
 11,
 15,
 9,
 9,
 9,
 2,
 6,
 9,
 11,
 2,
 16,
 18,
 11,
 18,
 15,
 13,
 13,
 1,
 1,
 9,
 16,
 18,
 3,
 1,
 11,
 9,
 11,
 11,
 7,
 13,
 11,
 15,
 18,
 4,
 4,
 9,
 4,
 18,
 15,
 16,
 4,
 9,
 13,
 15,
 15,
 16,
 1,
 11,
 4,
 18,
 11,
 9,
 15,
 15,
 9,
 18,
 11,
 2,
 16,
 11,
 9,
 9,
 11,
 15,
 7,
 ...]