**K-Means Clustering**

In [ ]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#loading datasets
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path = "/content/drive/MyDrive/emnist-letters-test.csv"

DFPD = pd.read_csv(path)

DF0 = DFPD.to_numpy()

In [ ]:
DF0.shape

(14799, 785)

In [ ]:
DF1 = DF0[:,1:]

In [ ]:
Int = [Int for Int in range(0,14798)]

In [ ]:
n = 14799
k = 19

In [ ]:
centroid = DF1[np.random.choice(Int, 19, replace = False)]
pd.DataFrame(centroid)

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
centroid.shape
DF1.shape

(14799, 784)

In [ ]:
euc_list = []

for i in range(19):
  euc_dist = 0
  euc_dist = np.sqrt(np.sum(((DF1 - centroid[i])**2), axis=1)) 
  
  euc_list.append(euc_dist)

  

pd.DataFrame(euc_list)

,0,1,2,3,4,5,6,7,8,9,...,14789,14790,14791,14792,14793,14794,14795,14796,14797,14798
0,2946.961995,2933.352348,3070.816667,2674.748212,2348.090288,3107.261978,3162.064990,3144.903178,2842.615521,2875.976530,...,2632.019947,2939.206185,2689.597182,2778.414296,2676.164606,2885.304490,2677.297145,2408.558698,2926.647741,2819.701225
1,2938.662961,2946.041582,3410.952653,2695.861829,3152.591791,2777.683927,3060.922410,2966.798780,3159.213510,2674.635302,...,3020.311242,2751.132858,2997.856901,2662.076445,3212.978369,2893.664286,2846.549666,3017.135396,3161.637234,2688.120905
2,3477.159904,2806.549839,2919.378530,2915.906377,2866.850537,2882.827605,3135.403483,3007.305771,3136.657297,2262.994255,...,3266.986838,2666.617520,3282.196978,3063.375589,3437.032586,2890.924074,3037.584896,3021.368068,3367.523274,2633.289008
3,2959.199385,2935.744539,3211.255051,2746.712216,2361.896695,2923.172421,3051.273996,2997.545329,3006.588931,2615.851104,...,2982.828356,2848.855384,2790.917233,3058.301816,3166.645070,2926.141828,2964.253700,2954.036730,3170.071135,2699.797215
4,3080.478697,3051.569760,3300.670386,2485.503973,3051.207630,2850.645015,3154.171048,3075.296408,3113.149370,3075.581734,...,2637.138032,2969.677592,2931.849416,2685.877883,2851.432096,3102.229843,2547.202387,2747.996543,3035.997859,2833.641297
5,2993.453524,2161.817060,2927.788585,2934.589750,2722.142355,2683.761912,2751.896437,2944.669931,3325.863196,2818.952642,...,2915.029674,2276.942248,2971.531255,2785.281135,2816.164768,2423.767522,2779.387163,2900.879867,2851.505567,2368.095860
6,3258.885699,2839.462097,3032.666154,2653.024877,3112.751677,3056.422091,3166.051484,3038.988483,3384.817277,3157.799550,...,2354.302020,2891.929460,2604.038018,2845.147272,2988.697041,2872.410312,2406.603623,2634.473382,2834.487608,2946.803013
7,3151.615776,3129.861179,3188.449466,3118.198037,3273.698367,3285.233325,3277.802313,3454.342050,3168.000000,2892.477139,...,2420.789541,2882.894726,2798.624305,2692.026189,2427.750811,2929.140318,3010.692777,2027.264166,2643.076995,2805.182347
8,3045.351047,2834.437510,3409.243464,2690.883498,3272.382618,2379.997269,2474.762413,2631.577854,3245.771249,2859.854367,...,3024.409860,2579.445095,3205.126675,2593.313325,2997.215207,2732.559240,2808.510993,3026.178944,3031.913092,2510.357943
9,2875.119128,2751.561193,2909.381721,2838.246466,3223.430626,2963.072054,3071.026213,3035.067545,3272.226765,2823.359347,...,2313.440728,2593.898996,2607.899154,2404.735952,2470.052226,2593.438837,2627.813350,2443.400499,2318.832465,2561.400008
10,3076.322317,2581.769936,3351.135181,2779.776969,3218.719311,2725.030092,2392.379778,2433.589941,3388.352845,2820.960297,...,2432.069695,2570.460076,2776.169123,2320.085774,2810.985059,2466.744819,2364.870821,2821.368640,2987.693927,2469.116239
11,3324.157938,3076.376277,3557.456676,2800.707946,3414.790916,2830.274898,3034.638034,2978.607225,3440.938535,3182.852494,...,2719.629387,2880.055208,2971.061763,2792.468263,2837.296601,3005.832830,2948.527599,2933.203027,2870.001045,2855.788508
12,3154.796031,2775.480679,3131.793416,2456.514401,2208.827517,2835.921367,3038.403199,3083.827978,2680.481673,3001.595576,...,3201.192278,3058.349228,3099.515769,3269.038850,3503.835613,2877.231829,2714.423143,2957.750497,3348.245809,2930.319437
13,2933.384905,2537.659946,2619.034364,2964.372446,2368.117818,2680.883996,2966.985507,3044.964039,2985.192624,3084.975040,...,3266.420518,2890.338561,2851.188699,3082.723471,3138.182117,2824.881236,3049.187761,2857.754538,3307.442365,2620.118890
14,3043.992280,2851.020870,2874.573881,2812.245722,2929.622501,2577.713134,2886.034823,2662.230268,3326.505824,2860.853194,...,3276.257774,2941.677583,3331.708120,3063.433694,3430.372137,3088.822753,2827.254852,3472.748623,3157.023440,3029.950000
15,3145.286156,3100.630259,3482.815097,2329.086946,3313.680431,2760.868161,3001.667703,2922.186168,3330.396523,3000.936354,...,2316.719016,2859.591404,2882.977454,2629.263015,2784.656352,3017.793896,2582.882498,2777.665387,2968.437131,2751.976926
16,3377.004294,2891.075405,3505.009272,3163.320249,3565.394368,3022.734524,2977.219844,2913.240979,3743.270495,3212.432723,...,3122.839413,2803.074384,3037.620450,2964.868800,3285.255546,2864.712027,2867.167069,3184.183726,3172.598619,3073.602447
17,2869.093411,3130.307653,3397.232845,3106.847598,3273.943799,3130.957521,3096.458138,3230.499961,3054.041093,3274.523324,...,2859.267913,2954.932994,2730.363895,2341.469197,2453.386843,3047.043157,2644.960491,3010.867483,2775.251880,2935.668408
18,3432.121793,2162.497861,2610.824774,2689.332073,3089.392011,2564.540115,2793.527519,2763.251889,3440.859776,3090.509020,...,2321.599018,2794.545759,2333.390237,2648.091955,2795.172982,2109.347055,2293.221533,2535.906544,2572.153572,2775.851581

In [ ]:
closest = np.argmin(euc_list, axis = 0)

In [ ]:
np.reshape(closest, (14799,1))

array([[17],
       [ 5],
       [18],
       ...,
       [ 7],
       [ 9],
       [ 5]])

In [ ]:
pd.DataFrame(closest)

        0
0      17
1       5
2      18
3      15
4      12
...    ..
14794  18
14795  18
14796   7
14797   9
14798   5

[14799 rows x 1 columns]

In [ ]:
arr = DF1[np.where(closest == 0)]

In [ ]:
cen = np.mean(arr, axis =0)

In [ ]:
cen.tolist()

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.004965243296921549,
 0.006951340615690168,
 0.0019860973187686196,
 0.0029791459781529296,
 0.0019860973187686196,
 0.0,
 0.003972194637537239,
 0.009930486593843098,
 0.007944389275074478,
 0.015888778550148957,
 0.011916583912611719,
 0.011916583912611719,
 0.012909632571996028,
 0.05163853028798411,
 0.027805362462760674,
 0.06752730883813307,
 0.1628599801390268,
 0.26613704071499505,
 0.25620655412115195,
 0.07447864945382324,
 0.0009930486593843098,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0029791459781529296,
 0.07646474677259185,
 0.1519364448857994,
 0.21946375372393248,
 0.2442899702085402,
 0.12313803376365443,
 0.19662363455809334,
 0.15988083416087387,
 0.15789473684210525,
 0.37040714995034757,
 0.7408142999006951,
 0.8560079443892751,
 1.1350546176762661,
 0.7864945382323734,
 0.7269116186693148,
 1.0009930486593843,
 1.9245283018867925,
 2.573982125124131,
 4.968222442899702,
 8.245283018867925,
 10.246276067527308,
 7.400198609731877,
 2.902681231380338,
 0.08738828202581926,
 0.0,
 0.0,
 0.0,
 0.0009930486593843098,
 0.1211519364448858,
 0.36643495531281034,
 0.6782522343594836,
 0.8480635551142006,
 0.8391261171797418,
 0.64746772591857,
 0.6355511420059583,
 1.0,
 1.7428003972194637,
 2.727904667328699,
 3.8897715988083417,
 4.068520357497517,
 4.289970208540218,
 4.375372393247269,
 5.187686196623635,
 8.42601787487587,
 14.456802383316782,
 23.004965243296922,
 32.49950347567031,
 39.112214498510426,
 38.08639523336643,
 26.67030784508441,
 10.185700099304865,
 0.3356504468718967,
 0.0,
 0.0,
 0.0,
 0.05263157894736842,
 0.46772591857000995,
 1.0218470705064548,
 1.6524329692154915,
 1.9026812313803376,
 1.9821251241310824,
 2.031777557100298,
 2.8252234359483617,
 3.579940417080437,
 4.9890764647467725,
 6.9860973187686195,
 9.351539225422046,
 11.063555114200597,
 12.873882820258192,
 15.969215491559087,
 22.742800397219465,
 35.98212512413108,
 52.14101290963257,
 67.64250248262165,
 76.85203574975174,
 78.84707050645481,
 69.99503475670308,
 47.96623634558093,
 18.681231380337636,
 0.8182720953326713,
 0.0,
 0.0,
 0.00893743793445879,
 0.3157894736842105,
 1.5431976166832175,
 2.83416087388282,
 4.362462760675273,
 5.133068520357497,
 5.833167825223436,
 6.168818272095333,
 7.080436941410129,
 8.5759682224429,
 11.117179741807348,
 15.615690168818272,
 21.95630585898709,
 29.26514399205561,
 38.404170804369414,
 51.53723932472691,
 69.73286991062562,
 93.9493545183714,
 116.20556107249256,
 130.2462760675273,
 132.91360476663357,
 124.4369414101291,
 100.67825223435949,
 65.80635551142007,
 23.556107249255213,
 0.929493545183714,
 0.0,
 0.0,
 0.012909632571996028,
 0.6335650446871897,
 2.8738828202581925,
 5.39622641509434,
 9.256206554121151,
 11.82720953326713,
 13.221449851042701,
 14.423038728897716,
 16.003972194637537,
 19.79245283018868,
 25.08540218470705,
 34.782522343594835,
 49.99801390268123,
 69.42701092353525,
 93.40913604766634,
 119.10327706057596,
 144.0764647467726,
 165.93048659384309,
 181.95829195630586,
 185.428997020854,
 173.09731876861966,
 149.39523336643495,
 113.82820258192652,
 70.08043694141013,
 23.392254220456802,
 0.871896722939424,
 0.0,
 0.0,
 0.016881827209533268,
 0.8987090367428004,
 4.162859980139027,
 9.420059582919563,
 15.167825223435948,
 19.513406156901688,
 22.48162859980139,
 25.915590863952335,
 31.944389275074478,
 40.98808341608739,
 52.20357497517379,
 71.61569016881828,
 100.73882820258193,
 133.07447864945382,
 164.95034756703078,
 188.94041708043693,
 203.76365441906654,
 208.18073485600794,
 202.62264150943398,
 188.54121151936445,
 167.17974180734856,
 138.7656405163853,
 103.93942403177756,
 63.0377358490566,
 20.25124131082423,
 0.7279046673286991,
 0.0,
 0.0,
 0.018867924528301886,
 1.1837140019860972,
 6.842105263157895,
 15.02979145978153,
 23.473684210526315,
 29.646474677259185,
 38.093346573982124,
 48.34558093346574,
 62.36345580933466,
 78.6454816285998,
 100.785501489573,
 129.30685203574976,
 162.5382323733863,
 192.22641509433961,
 211.51539225422044,
 215.22045680238332,
 204.33763654419067,
 186.04766633565043,
 166.84607745779545,
 146.50248262164845,
 125.39523336643495,
 107.54121151936445,
 85.15491559086395,
 53.68818272095333,
 17.08540218470705,
 0.5392254220456802,
 0.0,
 0.0,
 0.04369414101290963,
 2.316782522343595,
 12.09433962264151,
 24.49751737835154,
 37.270109235352535,
 51.08043694141013,
 69.22840119165839,
 87.00794438927507,
 105.67328699106257,
 129.30685203574976,
 152.85501489572988,
 176.28003972194637,
 199.56107249255214,
 214.0446871896723,
 212.15590863952335,
 189.6464746772592,
 155.57398212512413,
 126.05263157894737,
 103.4498510427011,
 89.91658391261171,
 81.77755710029791,
 78.12810327706057,
 68.98907646474677,
 46.114200595829196,
 16.07149950347567,
 0.6067527308838133,
 0.0,
 0.0,
 0.10526315789473684,
 4.7954319761668325,
 20.92850049652433,
 40.79940417080437,
 61.47666335650447,
 84.06156901688183,
 108.28997020854023,
 130.3614697120159,
 148.6782522343595,
 164.8490566037736,
 175.1261171797418,
 186.3982125124131,
 201.3356504468719,
 205.6772591857001,
 187.51042701092354,
 145.47964250248262,
 101.02879841112214,
 70.56703078450845,
 55.1390268123138,
 54.201588877855016,
 58.0695134061569,
 64.56802383316783,
 63.27110228401192,
 45.53128103277061,
 16.779543197616682,
 0.6504468718967229,
 0.0,
 0.0,
 0.19563058589870905,
 7.529294935451837,
 31.348560079443892,
 61.111221449851044,
 89.97020854021847,
 116.43098311817279,
 139.6196623634558,
 154.5829195630586,
 160.2462760675273,
 159.26812313803376,
 157.58093346573983,
 165.34061569016882,
 182.3227408142999,
 191.2542204568024,
 166.1638530287984,
 115.98609731876861,
 69.5511420059583,
 42.90168818272095,
 34.887785501489574,
 40.09831181727905,
 49.8927507447865,
 62.19165839126117,
 64.65541211519364,
 48.180734856007945,
 17.4051638530288,
 0.535253227408143,
 0.0,
 0.0,
 0.1916583912611718,
 10.840119165839127,
 44.95034756703078,
 83.8927507447865,
 117.1966236345581,
 137.36444885799403,
 146.75571002979146,
 143.94438927507449,
 133.08043694141014,
 120.84011916583913,
 117.27110228401192,
 132.4756703078451,
 167.02184707050645,
 184.4995034756703,
 155.4240317775571,
 101.11022840119166,
 56.249255213505464,
 33.42899702085402,
 28.97517378351539,
 35.908639523336646,
 49.72194637537239,
 64.34955312810328,
 67.93743793445879,
 49.88381330685203,
 17.309831181727905,
 0.4826216484607746,
 0.0,
 0.0,
 0.27805362462760674,
 14.372393247269116,
 58.270109235352535,
 104.29791459781529,
 133.35054617676266,
 140.58689175769612,
 131.25223435948362,
 112.39026812313803,
 93.0,
 78.84309831181729,
 81.5382323733863,
 112.66137040714995,
 161.74975173783514,
 183.7269116186693,
 152.28202581926516,
 97.27606752730884,
 53.55610724925521,
 32.442899702085406,
 28.680238331678254,
 37.821251241310826,
 54.53326713008938,
 70.50943396226415,
 73.54915590863952,
 52.13704071499504,
 17.133068520357497,
 0.522343594836147,
 0.0,
 0.0,
 0.42800397219463754,
 18.425024826216486,
 69.61569016881828,
 116.31181727904668,
 136.40119165839127,
 128.36345580933465,
 104.75670307845084,
 78.37735849056604,
 58.65342601787488,
 50.80933465739821,
 64.63555114200595,
 107.34359483614698,
 162.66931479642503,
 181.70109235352533,
 148.59582919563059,
 93.4111221449851,
 54.02085402184707,
 36.46971201588878,
 34.994041708043696,
 45.80635551142006,
 64.89374379344588,
 81.40714995034757,
 80.65541211519364,
 53.29592850049652,
 16.20754716981132,
 0.4031777557100298,
 0.0,
 0.0,
 0.6732869910625621,
 23.80238331678252,
 80.80536246276067,
 121.78748758689176,
 129.9235352532274,
 107.2025819265144,
 76.70605759682225,
 50.51837140019861,
 36.0506454816286,
 37.28798411122145,
 61.128103277060575,
 109.87984111221449,
 165.02780536246277,
 179.53525322740813,
 144.01588877855013,
 92.26911618669315,
 58.03674280039722,
 47.145978152929494,
 49.50446871896723,
 61.5253227408143,
 81.62959285004965,
 95.63654419066535,
 88.85799404170804,
 55.012909632572,
 15.497517378351539,
 0.4031777557100298,
 0.0,
 0.0,
 0.9364448857994042,
 29.779543197616682,
 90.8927507447865,
 127.30585898709037,
 123.2462760675273,
 91.83614697120159,
 59.85898709036743,
 38.17279046673287,
 30.167825223435948,
 39.05163853028798,
 69.36047666335651,
 119.95531281032771,
 168.86891757696128,
 176.41906653426017,
 140.46573982125125,
 95.4051638530288,
 69.13108242303873,
 64.44190665342602,
 70.785501489573,
 83.8987090367428,
 102.39126117179742,
 112.025819265144,
 96.59682224428997,
 55.611717974180735,
 15.507447864945382,
 0.4726911618669315,
 0.0,
 0.0,
 1.1072492552135054,
 34.388282025819265,
 98.79841112214498,
 131.85998013902682,
 121.09036742800397,
 88.32770605759683,
 60.01986097318768,
 43.30784508440914,
 41.372393247269116,
 55.5253227408143,
 89.15888778550149,
 136.87487586891757,
 172.59582919563059,
 172.01688182720955,
 139.6633565044687,
 103.63654419066535,
 85.98113207547169,
 85.81529294935451,
 94.48460774577954,
 108.12810327706057,
 122.93445878848064,
 124.22641509433963,
 101.27507447864946,
 57.042701092353525,
 15.860973187686197,
 0.4528301886792453,
 0.0,
 0.0,
 1.2343594836146972,
 35.717974180734856,
 103.03574975173784,
 135.2224428997021,
 126.32174776564051,
 98.18768619662363,
 74.42502482621649,
 65.24925521350546,
 71.1330685203575,
 91.266137040715,
 124.59185700099304,
 160.29294935451838,
 179.92750744786494,
 173.26911618669314,
 147.41608738828202,
 120.05958291956306,
 109.6206554121152,
 111.29493545183713,
 118.20754716981132,
 128.6077457795432,
 135.1777557100298,
 128.17576961271104,
 99.14200595829196,
 54.595829195630586,
 15.370407149950347,
 0.47765640516385305,
 0.0,
 0.0,
 1.2730883813306852,
 33.77457795431976,
 97.60675273088381,
 133.92055610724927,
 134.08540218470705,
 116.5441906653426,
 102.96027805362463,
 103.24230387288978,
 115.01092353525323,
 135.05561072492551,
 159.14399205561074,
 175.64448857994043,
 180.78848063555114,
 171.08639523336643,
 153.39721946375371,
 135.68023833167825,
 125.46971201588877,
 123.36544190665343,
 124.30685203574976,
 126.42005958291956,
 125.67030784508441,
 113.81727904667329,
 85.2780536246276,
 46.00297914597815,
 13.456802383316782,
 0.4667328699106256,
 0.0,
 0.0,
 1.041708043694141,
 29.869910625620655,
 85.214498510427,
 122.84707050645481,
 135.05561072492551,
 130.4309831181728,
 129.06653426017874,
 135.1827209533267,
 146.21648460774577,
 159.45183714001985,
 167.0446871896723,
 167.3982125124131,
 162.9553128103277,
 152.84508440913604,
 136.88977159880835,
 122.05461767626613,
 111.98411122144985,
 106.03475670307846,
 102.01290963257199,
 100.13505461767626,
 96.01787487586891,
 82.80238331678252,
 61.130089374379345,
 33.682224428997024,
 10.132075471698114,
 0.3336643495531281,
 0.0,
 0.0,
 0.8182720953326713,
 23.857994041708043,
 68.7914597815293,
 103.53028798411123,
 121.88679245283019,
 127.66137040714995,
 131.21847070506456,
 136.961271102284,
 140.17874875868918,
 139.53028798411123,
 131.7279046673287,
 122.85799404170804,
 116.92850049652434,
 110.6772591857001,
 99.49056603773585,
 86.05561072492551,
 76.38430983118172,
 70.25422045680239,
 65.61767626613704,
 62.85700099304866,
 59.93147964250248,
 52.03078450844092,
 38.63356504468719,
 21.50248262164846,
 6.723932472691162,
 0.20854021847070506,
 0.0,
 0.0,
 0.5342601787487586,
 17.306852035749753,
 49.97914597815293,
 77.87586891757697,
 94.34657398212512,
 101.68917576961272,
 103.97318768619662,
 101.2840119165839,
 95.31479642502482,
 86.02085402184707,
 76.14597815292949,
 67.77457795431977,
 64.73485600794439,
 62.61668321747766,
 54.84011916583913,
 45.15292949354519,
 37.77259185700099,
 34.056603773584904,
 32.72889771598808,
 31.04170804369414,
 29.825223435948363,
 26.604766633565045,
 20.23038728897716,
 11.646474677259185,
 4.048659384309831,
 0.12711022840119166,
 0.0,
 0.0,
 0.2701092353525323,
 10.031777557100298,
 32.09930486593843,
 51.18867924528302,
 61.55312810327706,
 63.50248262164846,
 62.39126117179742,
 55.749751737835155,
 47.26017874875869,
 39.36643495531281,
 32.62164846077458,
 28.837140019860975,
 29.46077457795432,
 30.528301886792452,
 26.64448857994042,
 20.76067527308838,
 16.19165839126117,
 14.494538232373387,
 13.750744786494538,
 13.819265143992055,
 13.069513406156902,
 10.99503475670308,
 8.01588877855015,
 4.523336643495531,
 1.2442899702085402,
 0.011916583912611719,
 0.0,
 0.0,
 0.07348560079443893,
 4.629592850049653,
 14.901688182720953,
 24.25124131082423,
 29.11519364448858,
 29.047666335650447,
 26.278053624627606,
 21.94637537239325,
 17.37040714995035,
 12.574975173783516,
 9.5759682224429,
 9.340615690168818,
 10.679245283018869,
 12.291956305858987,
 10.187686196623634,
 7.609731876861966,
 5.790466732869911,
 4.944389275074479,
 4.499503475670308,
 4.690168818272095,
 4.012909632571996,
 2.830188679245283,
 2.139026812313803,
 1.038728897715988,
 0.19761668321747766,
 0.0,
 0.0,
 0.0,
 0.011916583912611719,
 1.3147964250248263,
 4.2045680238331675,
 6.088381330685204,
 6.608738828202582,
 6.3892750744786495,
 5.441906653426018,
 3.7934458788480634,
 2.1747765640516383,
 1.2909632571996028,
 0.968222442899702,
 1.5789473684210527,
 2.3157894736842106,
 2.5561072492552137,
 2.0556107249255215,
 1.3565044687189671,
 0.9851042701092354,
 0.7557100297914597,
 0.6653426017874876,
 0.730883813306852,
 0.5868917576961271,
 0.4041708043694141,
 0.43098311817279045,
 0.16881827209533268,
 0.01787487586891758,
 0.0,
 0.0,
 0.0,
 0.0,
 0.031777557100297914,
 0.15491559086395235,
 0.18669314796425024,
 0.13406156901688182,
 0.18867924528301888,
 0.1499503475670308,
 0.09433962264150944,
 0.024826216484607744,
 0.024826216484607744,
 0.021847070506454815,
 0.03277060575968222,
 0.06752730883813307,
 0.038728897715988087,
 0.031777557100297914,
 0.05461767626613704,
 0.013902681231380337,
 0.00893743793445879,
 0.004965243296921549,
 0.006951340615690168,
 0.00893743793445879,
 0.003972194637537239,
 0.005958291956305859,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [2]:
def Kmeans_model(DF1):
  centroid = DF1[np.random.choice(Int, 19, replace = False)]  

  euc_list = []
  for k in range(1000):
   for i in range(19):
    euc_dist = 0
    euc_dist = np.sqrt(np.sum(((DF1 - centroid[i])**2), axis=1)) 
  
   euc_list.append(euc_dist)

   closest = np.argmin(euc_list, axis = 0) 
  
   for j in range(19):
    arr = DF1[np.where(closest == i)]
    cen = 0
    cen = np.mean(arr, axis =0)
    centroid[i] = cen